### ISSUE TITLE
Unable to Parse scss file

### ISSUE THREAD

**Issue by munishshukla** [dropbox/typed-css-modules-webpack-plugin#11]
I have a loop inside the scss file and due to that not able to create .d.ts file, when I remove that it's worked fine.

SCSS File Content

`$icons: ("eye": "\f112", "start": "\f12e", "stop": "\f12f");
@each $name, $glyph in $icons {
  .icon-#{$name}:before {
    display: inline-block;
    font-family: "Icon Font";
    content: $glyph;
  }
}`

Error 
`CssSyntaxError: /app/style.scss:3:11: Unknown word {$name}`

**Comment by pyrocat101** [comment]
What does your configuration look like? Do you set `postCssPlugins` options?

**Comment by proteye** [comment]
@pyrocat101 I have the same problem. I don't set `postCssPlugins` option.
`    new TypedCssModulesPlugin({
      globPattern: 'app/**/*.{css,scss,sass}'
    }),
`

**Comment by proteye** [comment]
`CssSyntaxError: /app/styles/smart-grid.scss:40:7: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

  38 | 
  39 | @mixin col-offsets($type){
> 40 |     #{$type}-left: $offset_one_side;
     |       ^
  41 |     #{$type}-right: $offset_one_side;
  42 | }
`

**Comment by pyrocat101** [comment]
@proteye PRs welcome :)
