### ISSUE TITLE
different endOfLine on windows

### ISSUE THREAD

**Issue by Topppy** [dropbox/typed-css-modules-webpack-plugin#12]
we add  typed-css-modules-webpack-plugin on Mac and push to the git.
After clone and yarn install on windows,  all the *.css.d.ts files are changed.

![屏幕截图(3)](https://user-images.githubusercontent.com/9689442/80685369-b2d4c600-8af9-11ea-9d55-dc61060c2673.png)

**Comment by longlho** [comment]
That seems like a git setting issue w/ CLRF that you have?

**Comment by Topppy** [comment]
> git setting issue w/ CLR

Thanks for your help, my mistake, it is git autocrlf setting issue
